### ISSUE TITLE
提示 compile failed: SyntaxError: Parenthesized pattern！

### ISSUE THREAD

**Issue by fxjs** [ErosZy/sablejs#42]
转换vite打包后的代码，报这个错，求解？谢谢
`
[ryan@ryanos dist]$ ~/soft/sablejs-linux-x64 -i sinan.es.js -o test.js

[ERROR] compile failed: SyntaxError: Parenthesized pattern (2:22)
    at Parser.<anonymous> (/snapshot/sablejs-private-repo/node_modules/acorn/dist/acorn.js:3460:15)
    at Parser.checkPatternErrors (/snapshot/sablejs-private-repo/node_modules/acorn/dist/acorn.js:773:29)
    at Parser.toAssignable (/snapshot/sablejs-private-repo/node_modules/acorn/dist/acorn.js:1955:47)
    at Parser.parseMaybeAssign (/snapshot/sablejs-private-repo/node_modules/acorn/dist/acorn.js:2476:23)
    at Parser.parseVar (/snapshot/sablejs-private-repo/node_modules/acorn/dist/acorn.js:1299:26)
    at Parser.parseVarStatement (/snapshot/sablejs-private-repo/node_modules/acorn/dist/acorn.js:1163:10)
    at Parser.parseStatement (/snapshot/sablejs-private-repo/node_modules/acorn/dist/acorn.js:911:19)
    at Parser.parseTopLevel (/snapshot/sablejs-private-repo/node_modules/acorn/dist/acorn.js:813:23)
    at Parser.parse (/snapshot/sablejs-private-repo/node_modules/acorn/dist/acorn.js:586:17)
    at Function.parse (/snapshot/sablejs-private-repo/node_modules/acorn/dist/acorn.js:636:37)
`

**Comment by ErosZy** [comment]
@fxjs 仅支持 es5.1 版本的语法。
